title: Geri's Logs
url: "https://logs.gerardgascon.com"
baseurl: ""

description:
  This is a place to simply log my projects' progress.

feed_items: 10
feed_update_period: daily
feed_update_frequency: 1

collections:
  logs:
    output: true
    permalink: /logs/:title

plugins:
  - jekyll-toc

toc:
  list_class: incremental
  list_id: null